// Generated by scripts/build-region-maps.py. Content hashes refresh cached maps.
export const regionalAssets: Record<string,string> = {
 "北海道・東北": "./assets/regions/hokkaido-tohoku.svg?v=13076578d231",
 "関東": "./assets/regions/kanto.svg?v=23d3f4262ea2",
 "中部": "./assets/regions/chubu.svg?v=f7d224a44583",
 "近畿": "./assets/regions/kinki.svg?v=a7bdbbc3dd11",
 "中国": "./assets/regions/chugoku.svg?v=3ad955f007e3",
 "四国": "./assets/regions/shikoku.svg?v=0e6abce54a14",
 "九州・沖縄": "./assets/regions/kyushu-okinawa.svg?v=328cff369cd4"
};
